

nodeSelector: {}

tolerations: []

affinity: {}


ingress:
  enabled: true
  host: "ticketing.dev"


auth:
  replicaCount: 1

  image:
    repository: mohammedrisvanvm/auth
    tag: latest

  mongoUri: "mongodb://ticketing-auth-mongo-srv:27017/auth"

authMongo:
  replicaCount: 1

  image:
    repository: mongo
    tag: latest


nats:
  replicaCount: 1
  image:
    repository: nats-streaming
    tag: "0.17.0"

orders:
  replicaCount: 1
  image:
    repository: mohammedrisvanvm/orders
    tag: latest

tickets:
  replicaCount: 1
  image:
    repository: mohammedrisvanvm/tickets
    tag: latest

ticketsMongo:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest

ordersMongo:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest

expiration:
  image:
    repository: mohammedrisvanvm/expiration
    tag: latest
  replicaCount: 1

redis:
  image:
    repository: redis
    tag: latest
